"""Release gate for the bundled PDF user guide.

Guards the rule that broke v0.1.1-v0.1.3: every link in the shipped manual must
be a public HTTPS address that carries no build-machine residue. The defect
appeared in two forms from two different PDF generators, so a check for "file:"
alone is not enough, and an HTTPS prefix alone is not proof of safety.

The PDF cases below are built in-process rather than committed as binary
fixtures, so the suite exercises real parsing without carrying opaque files.
"""

import subprocess
import sys
import tempfile
import unittest
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]
SCRIPTS_ROOT = REPO_ROOT / "scripts"
if str(SCRIPTS_ROOT) not in sys.path:
    sys.path.insert(0, str(SCRIPTS_ROOT))

import check_pdf_links as gate  # noqa: E402

BACKSLASH = chr(92)

try:  # pypdf is a build-time dependency (requirements-build.txt), not a runtime one.
    import pypdf  # noqa: F401

    HAS_PYPDF = True
except ImportError:
    HAS_PYPDF = False

NEEDS_PYPDF = unittest.skipUnless(
    HAS_PYPDF,
    "pypdf not installed; install requirements-build.txt to run the parsing tests. "
    "The gate itself fails closed without it, which is covered separately.",
)


def _pdf(uri, hex_encode=False, subject=None):
    """Smallest PDF that pypdf accepts and that carries one link annotation.

    `hex_encode` stores the URI as a PDF hexadecimal string. That is ordinary
    PDF syntax, and it means the target never appears literally in the file --
    the case that slipped past a raw-bytes-only scan.
    """
    if hex_encode:
        target = "<" + uri.encode("ascii").hex().upper() + ">"
    else:
        target = "(" + uri + ")"

    objects = [
        "<</Type /Catalog /Pages 2 0 R>>",
        "<</Type /Pages /Kids [3 0 R] /Count 1>>",
        "<</Type /Page /Parent 2 0 R /MediaBox [0 0 595 842] /Annots [4 0 R]>>",
        "<</Type /Annot /Subtype /Link /Rect [0 0 100 20] /Border [0 0 0]"
        " /A <</Type /Action /S /URI /URI " + target + ">>>>",
    ]
    if subject is not None:
        objects.append("<</Subject (" + subject + ")>>")

    out = bytearray(b"%PDF-1.4\n")
    offsets = []
    for number, body in enumerate(objects, start=1):
        offsets.append(len(out))
        out += (str(number) + " 0 obj\n" + body + "\nendobj\n").encode("latin-1")

    xref_at = len(out)
    out += ("xref\n0 " + str(len(objects) + 1) + "\n").encode("latin-1")
    out += b"0000000000 65535 f \n"
    for offset in offsets:
        out += ("%010d 00000 n \n" % offset).encode("latin-1")

    trailer = "<</Size " + str(len(objects) + 1) + " /Root 1 0 R"
    if subject is not None:
        trailer += " /Info " + str(len(objects)) + " 0 R"
    trailer += ">>"
    out += ("trailer\n" + trailer + "\nstartxref\n" + str(xref_at) + "\n%%EOF\n").encode("latin-1")
    return bytes(out)


class UriPolicyTests(unittest.TestCase):
    def test_allows_https_and_the_author_mailto(self):
        for uri in (
            "https://github.com/gtree965/bashi-voice-factory-privacy",
            "https://gitee.com/gtree965/",
            "mailto:ncorecpu@gmail.com",
        ):
            self.assertTrue(gate.uri_is_allowed(uri), uri)

    def test_rejects_both_observed_forms_of_the_defect(self):
        # v0.1.3 shipped the first form, v0.1.0-v0.1.2 the second.
        for uri in (
            "file:///C:/Users/someone/AppData/Local/Temp/build/scratchpad/pdf/LICENSE",
            "http://markdownpanel-virtualhost/LICENSE",
        ):
            self.assertFalse(gate.uri_is_allowed(uri), uri)

    def test_https_prefix_alone_is_not_enough(self):
        for uri in (
            "https://example.com/C:/Users/someone/Documents/LICENSE",
            "https://files.fm/u/retired",
            "https://example.com/tmp/pdfbuild/LICENSE",
        ):
            self.assertFalse(gate.uri_is_allowed(uri), uri)

    def test_rejects_plain_http_and_other_mailto(self):
        self.assertFalse(gate.uri_is_allowed("http://example.com/"))
        self.assertFalse(gate.uri_is_allowed("mailto:someone-else@example.com"))


class ForbiddenSequenceTests(unittest.TestCase):
    def test_flags_every_documented_category(self):
        cases = {
            "file:///C:/Users/someone/x": "file:",
            "C:" + BACKSLASH + "Users" + BACKSLASH + "someone": "Users",
            "C:" + BACKSLASH + "tmp" + BACKSLASH + "build": "tmp",
            "/tmp/pdfbuild": "tmp",
            "...OneDrive/Documents...": "OneDrive",
            "/AppData/Local/Temp/x/": "Temp",
            "...scratchpad/pdf...": "scratchpad",
            "http://markdownpanel-virtualhost/LICENSE": "markdownpanel",
            "https://files.fm/u/abcdef": "files.fm",
            "generated by claude": "claude",
            "12345678-1234-1234-1234-123456789abc": "1234",
        }
        for payload, expected in cases.items():
            hits = gate.forbidden_sequences(payload)
            self.assertTrue(hits, "expected a hit for " + repr(payload))
            self.assertTrue(
                any(expected.lower() in hit.lower() for hit in hits),
                repr(payload) + " -> " + repr(hits) + ", wanted " + repr(expected),
            )

    def test_keeps_the_hardware_brand_the_manual_names(self):
        # "Snapdragon X Copilot+ PC" is a product, not a tool credit, and the
        # manual wraps it across lines, so the exception cannot rely on " PC".
        self.assertEqual([], gate.forbidden_sequences("Snapdragon X Copilot+ PC"))
        self.assertEqual([], gate.forbidden_sequences("Snapdragon X Copilot+"))

    def test_passes_a_clean_payload(self):
        clean = (
            "https://github.com/gtree965/bashi-voice-factory-privacy "
            "https://gitee.com/gtree965/ mailto:ncorecpu@gmail.com"
        )
        self.assertEqual([], gate.forbidden_sequences(clean))


@NEEDS_PYPDF
class RealPdfTests(unittest.TestCase):
    """End to end over actual parsed PDFs, not the helpers in isolation."""

    def _check(self, data):
        with tempfile.TemporaryDirectory() as temporary:
            path = Path(temporary) / "guide.pdf"
            path.write_bytes(data)
            return gate.check(path)

    def test_accepts_a_clean_document(self):
        self.assertEqual([], self._check(_pdf("https://gitee.com/gtree965/")))

    def test_rejects_a_local_path_link(self):
        problems = self._check(_pdf("file:///C:/Users/someone/pdf/LICENSE"))
        self.assertTrue(any("link target" in p for p in problems), problems)

    def test_rejects_hex_encoded_targets_that_never_appear_literally(self):
        # The target is stored as hex, so a raw byte scan cannot see it.
        for uri in (
            "https://files.fm/u/retired",
            "https://example.com/C:/Users/someone/Documents/LICENSE",
        ):
            data = _pdf(uri, hex_encode=True)
            self.assertNotIn(uri.encode(), data, "fixture should hide the target")
            problems = self._check(data)
            self.assertTrue(any("link target" in p for p in problems), (uri, problems))

    def test_rejects_residue_hiding_in_document_metadata(self):
        data = _pdf(
            "https://gitee.com/gtree965/",
            subject="claude 12345678-1234-1234-1234-123456789abc C:/tmp/pdfbuild",
        )
        problems = self._check(data)
        self.assertTrue(any("metadata" in p for p in problems), problems)


@NEEDS_PYPDF
class CommandLineTests(unittest.TestCase):
    def _run(self, *args):
        return subprocess.run(
            [sys.executable, "-B", str(SCRIPTS_ROOT / "check_pdf_links.py")] + list(args),
            capture_output=True,
        ).returncode

    def test_exit_codes(self):
        with tempfile.TemporaryDirectory() as temporary:
            good = Path(temporary) / "good.pdf"
            good.write_bytes(_pdf("https://gitee.com/gtree965/"))
            bad = Path(temporary) / "bad.pdf"
            bad.write_bytes(_pdf("https://files.fm/u/retired", hex_encode=True))

            self.assertEqual(0, self._run(str(good)))
            self.assertEqual(1, self._run(str(bad)))
            self.assertEqual(2, self._run(str(Path(temporary) / "missing.pdf")))
            self.assertEqual(2, self._run())


class FailClosedTests(unittest.TestCase):
    def test_missing_parser_blocks_instead_of_passing(self):
        """Without a parser the answer must be "no", never "probably fine"."""
        import importlib

        real_import = __builtins__["__import__"] if isinstance(__builtins__, dict) else __builtins__.__import__

        def deny_pypdf(name, *args, **kwargs):
            if name == "pypdf":
                raise ImportError("simulated missing pypdf")
            return real_import(name, *args, **kwargs)

        with tempfile.TemporaryDirectory() as temporary:
            path = Path(temporary) / "guide.pdf"
            path.write_bytes(_pdf("https://gitee.com/gtree965/"))
            builtins_module = importlib.import_module("builtins")
            builtins_module.__import__ = deny_pypdf
            try:
                with self.assertRaises(SystemExit):
                    gate.check(path)
            finally:
                builtins_module.__import__ = real_import


if __name__ == "__main__":
    unittest.main()
